# Generated by Django 4.2.23 on 2025-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['order'], name='disputes_di_order_i_949626_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['initiator'], name='disputes_di_initiat_4666e1_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_di_status_124397_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['moderator'], name='disputes_di_moderat_c79efc_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['created_at'], name='disputes_di_created_ccc858_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', 'created_at'], name='disputes_di_status_edf3a9_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['moderator', 'status'], name='disputes_di_moderat_6b6458_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['dispute'], name='disputes_di_dispute_06a374_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['sender'], name='disputes_di_sender__08ef0f_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['created_at'], name='disputes_di_created_a42318_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_di_dispute_933084_idx'),
        ),
    ]
