# Generated by Django 4.2.23 on 2025-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user'], name='searches_se_user_id_191fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['query'], name='searches_se_query_85becf_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['searched_at'], name='searches_se_searche_9acd97_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'searched_at'], name='searches_se_user_id_d7391c_idx'),
        ),
    ]
