# Generated by Django 4.2.21 on 2025-05-09 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_terms',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a accepté les conditions générales."),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'utilisateur a accepté les conditions générales.", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_to_newsletter',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur est abonné à la newsletter."),
        ),
    ]
