# Generated by Django 4.2.23 on 2025-06-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_accepted_terms_user_accepted_terms_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0, help_text="Note moyenne de l'utilisateur en tant que vendeur."),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', help_text="Définit le rôle de l'utilisateur (particulier ou professionnel).", max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text="Identifiant du compte Stripe de l'utilisateur.", max_length=255, null=True),
        ),
    ]
