# Generated by Django 4.2.23 on 2025-06-19 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_email_otp_user_email_otp_expiry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_type",
            field=models.CharField(
                choices=[
                    ("billing", "Facturation"),
                    ("delivery", "Livraison"),
                    ("both", "Facturation et Livraison"),
                    ("company", "Entreprise"),
                ],
                default="delivery",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ProfessionalInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                (
                    "siret_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("vat_number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "company_address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_info",
                        to="accounts.address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
