# Generated by Django 4.2.23 on 2025-06-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_rating_user_role_user_stripe_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_kyc_verified',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a complété le KYC avec succès."),
        ),
    ]
