# Generated by Django 4.2.23 on 2025-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_address_address_type_professionalinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['stripe_account_id'], name='accounts_us_stripe__06deba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['stripe_customer_id'], name='accounts_us_stripe__0997f8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_seller', 'is_email_verified'], name='accounts_us_is_sell_534450_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_buyer'], name='accounts_us_is_buye_598603_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_email_verified'], name='accounts_us_is_emai_fb6e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='accounts_us_role_1fa9a5_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['stripe_account_status'], name='accounts_us_stripe__678e41_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_kyc_verified'], name='accounts_us_is_kyc__7e3cfe_idx'),
        ),
    ]
