# Generated by Django 4.2.23 on 2025-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_kyc_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
