# Generated by Django 4.2.23 on 2025-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_total_sales_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_sales_amount',
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_account_status',
            field=models.CharField(blank=True, help_text="État actuel du compte Stripe (par ex. 'incomplete', 'completed', 'verified', etc.)", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
