# Generated by Django 4.2.20 on 2025-06-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0005_alter_user_options_user_accounts_us_email_74c8d6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_token",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="password_reset_token_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
