# Generated by Django 4.2.23 on 2025-06-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_total_sales_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, choices=[('verified', 'Vérifié'), ('incomplete', 'Incomplet'), ('pending', 'En attente'), ('restricted', 'Restreint')], default='incomplete', help_text="Identifiant du compte Stripe de l'utilisateur.", max_length=255, null=True),
        ),
    ]
