# Generated by Django 4.2.23 on 2025-06-18 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text="Identifiant du compte Stripe de l'utilisateur.", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='stripe_account_status',
            field=models.CharField(blank=True, choices=[('verified', 'Vérifié'), ('incomplete', 'Incomplet'), ('pending', 'En attente'), ('restricted', 'Restreint')], default='incomplete', help_text="État actuel du compte Stripe (par ex. 'incomplete', 'completed', 'verified', etc.)", max_length=100, null=True),
        ),
    ]
