# Generated by Django 4.2.23 on 2025-06-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_user_stripe_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant du client Stripe pour les paiements",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Identifiant de l'abonnement premium Stripe",
                max_length=255,
                null=True,
            ),
        ),
    ]
