# Generated by Django 4.2.23 on 2025-06-18 09:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_collection_collectionitem_collection_variants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0004_use_listing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("buyer", "listing")},
        ),
    ]
