# Generated by Django 4.2.23 on 2025-06-18 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_collection_collectionitem_collection_variants"),
        ("orders", "0005_use_listing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="listing",
        ),
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_net_amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_processing_fee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_shipping_fee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="seller_transaction_fee",
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="products.listing",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
            ],
        ),
    ]
