# Generated by Django 4.2.23 on 2025-06-18 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('tcg_types', models.JSONField(default=list)),
                ('description', models.TextField(blank=True, null=True)),
                ('displayable', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricehistory',
            name='product',
        ),
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='collection',
            new_name='block',
        ),
        migrations.RemoveField(
            model_name='product',
            name='language',
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('name', 'block', 'series'), name='unique_product'),
        ),
        migrations.DeleteModel(
            name='PriceHistory',
        ),
        migrations.AddField(
            model_name='variant',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.condition'),
        ),
        migrations.AddField(
            model_name='variant',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.grade'),
        ),
        migrations.AddField(
            model_name='variant',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.language'),
        ),
        migrations.AddField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product'),
        ),
        migrations.AddField(
            model_name='variant',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.version'),
        ),
        migrations.AddField(
            model_name='listing',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='products.product'),
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.variant'),
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_languages',
            field=models.ManyToManyField(blank=True, to='products.language'),
        ),
        migrations.AddField(
            model_name='product',
            name='allowed_versions',
            field=models.ManyToManyField(blank=True, to='products.version'),
        ),
        migrations.AddConstraint(
            model_name='variant',
            constraint=models.UniqueConstraint(fields=('product', 'language', 'version', 'condition', 'grade'), name='unique_variant_combination'),
        ),
    ]
