# Generated by Django 4.2.23 on 2025-06-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_condition_grade_language_listing_variant_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condition',
            name='is_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grade',
            name='grader',
            field=models.CharField(choices=[('PSA', 'PSA'), ('PCA', 'PCA'), ('BGS', 'BGS'), ('CGC', 'CGC'), ('CCC', 'CCC'), ('SGC', 'SGC'), ('OTHER', 'Autre')], default='PSA', max_length=20),
        ),
    ]
