# Generated by Django 4.2.23 on 2025-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_searchhistory'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='products_li_status_035c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller'], name='products_li_seller__44bac9_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['product'], name='products_li_product_cc3e83_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['variant'], name='products_li_variant_4d0e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['price'], name='products_li_price_8f97f6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['created_at'], name='products_li_created_b2eaff_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'price'], name='products_li_status_f8ed88_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['seller', 'status'], name='products_li_seller__175f23_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['product', 'status'], name='products_li_product_25d67d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['stock'], name='products_li_stock_d7b021_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tcg_type'], name='products_pr_tcg_typ_6f8aab_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['block'], name='products_pr_block_fb5c00_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['series'], name='products_pr_series_782ea0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['tcg_type', 'name'], name='products_pr_tcg_typ_279b2e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['block', 'series'], name='products_pr_block_64732a_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product'], name='products_va_product_18d9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['language'], name='products_va_languag_a70413_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['version'], name='products_va_version_fa72ed_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['condition'], name='products_va_conditi_7c713a_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['grade'], name='products_va_grade_i_5867d3_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'language'], name='products_va_product_cf57ed_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['condition', 'grade'], name='products_va_conditi_9a4206_idx'),
        ),
    ]
